# Generated by Django 4.2.4 on 2023-08-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('release_year', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('latest_model', models.BooleanField()),
            ],
        ),
    ]
