# Generated by Django 4.2.4 on 2023-08-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_device_latest_model_device_colours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='category',
            new_name='operating_system',
        ),
        migrations.RemoveField(
            model_name='device',
            name='colours',
        ),
        migrations.AddField(
            model_name='device',
            name='type',
            field=models.CharField(default=2000, max_length=100),
            preserve_default=False,
        ),
    ]
